### ISSUE TITLE
analyzer doesn't work - need help

### ISSUE THREAD

**Issue by jonasdoelling** [klayveR/python-poe-timeless-jewel#1]
Hallo Tobias,

erstmal danke für deine Mühe! 

An und für sich sollte ich alles richtig gemacht haben. Habe bereits auch schon einige Jewels aufgenommen. 
Allerdings bekommt er das analisieren nicht hin. 

run_analyzer ohne Admin
```Analyzing jewel socket '1563625648'
Traceback (most recent call last):
  File "C:\python-poe-timeless-jewel-master/scripts/analyzer.py", line 409, in <module>
    analyzeJewels(dirs["jewel"])
  File "C:\python-poe-timeless-jewel-master/scripts/analyzer.py", line 299, in analyzeJewels
    nodes = imagesInDirToStrings(jewelDir)
  File "C:\python-poe-timeless-jewel-master/scripts/analyzer.py", line 36, in imagesInDirToStrings
    lines = OCR.imageToStringArray(image)
  File "C:\python-poe-timeless-jewel-master\scripts\ocr.py", line 36, in imageToStringArray
    config='--oem 3 --psm 12 poe')
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string
    }[output_type]()
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 308, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 186, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your path
Drücken Sie eine beliebige Taste . . .
```

Mit admin:
`Drücken Sie eine beliebige Taste . . .`

analyzer.py  über die IDE gestartet (f5 run module)
```
====== RESTART: C:\python-poe-timeless-jewel-master\scripts\analyzer.py ======
Analyzing jewel socket '1563625648'

Traceback (most recent call last):
  File "C:\python-poe-timeless-jewel-master\scripts\analyzer.py", line 409, in <module>
    analyzeJewels(dirs["jewel"])
  File "C:\python-poe-timeless-jewel-master\scripts\analyzer.py", line 299, in analyzeJewels
    nodes = imagesInDirToStrings(jewelDir)
  File "C:\python-poe-timeless-jewel-master\scripts\analyzer.py", line 36, in imagesInDirToStrings
    lines = OCR.imageToStringArray(image)
  File "C:\python-poe-timeless-jewel-master\scripts\ocr.py", line 36, in imageToStringArray
    config='--oem 3 --psm 12 poe')
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string
    }[output_type]()
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 308, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 186, in run_tesseract
    raise TesseractNotFoundError()
TesseractNotFoundError: tesseract is not installed or it's not in your path
>>> 
```

Wäre voll nett wenn du mir helfen könntest, würde gerne ein paar Jewels checken lassen :)

**Comment by DaCurse** [comment]
The exception tells you the problem: `TesseractNotFoundError: tesseract is not installed or it's not in your path`

**Comment by jonasdoelling** [comment]
Well yeah thats right, but i have tesseract installed, exactly where it should be and also followed his instruction. 

Edit: It seems i was wrong O.o
I reinstalled it on a different place (where the run_analyze.cmd is) and now it "works" 

But unfortunellty its crashing again: 
starting with bash script => 
```
Analyzing jewel socket '1563625648'
88/88: [------------------------------------------------->] 100%
Traceback (most recent call last):
  File "scripts/analyzer.py", line 409, in <module>
    analyzeJewels(dirs["jewel"])
  File "scripts/analyzer.py", line 318, in analyzeJewels
    if jewelInfo["socket"]["index"] == -1:
TypeError: list indices must be integers, not str
```

its just a simple TypeError (so converting the indices should fix this. 

To bad that I can't code python :(

Line 318-320
```
if jewelInfo["socket"]["index"] == -1:
            print "\nWarning!\nThe jewel socket for this jewel couldn't be determined. Make sure every node in the jewel radius is fully visible when capturing.\n"
            print "If you want to recapture this jewel, you have to delete " + os.path.join(dirs["jewelDone"], str(jewelId) + ".png")
```
I also deleted my first records and did one again, but that also din't help.


Update2:
I changed 
  if jewelInfo["socket"]["index"] == -1:
to
  if result["socket"]["index"] == -1:

because it made more sence to me. 

The analyzer did run through, but now the javascript throws expections.
Because there are a lot of informations missing in the json that we want to load.


Well I gona sleep now, maybe I can figure it out tomorrow :)
And thanks for the help.

**Comment by klayver** [comment]
I removed that part from the script temporarily. Simply redownload `analyzer.py` and replace it in the `scripts/` folder. Thanks for the report!

**Comment by jonasdoelling** [comment]
Well the analyzer now works. 

But the javascript still cant handle the json. 

Here is a part of the generated json that the analyzer created:
```
{
    "nodes": [
        {
            "name": "Disciple of the Unyielding", 
            "passives": [
                "+1 to Minimum Endurance Charges", 
                "5% chance to gain an Endurance Charge on Kill", 
                "5% increased Damage per Endurance Charge"
            ], 
            "type": "notable", 
            "x": -0.08196721311475409, 
            "y": 0.8337236533957846
        }, 
        {
            "name": "Dervish", 
            "passives": [
                "+2% Chance to Block Attack Damage while Dual Wielding", 
                "24% increased Weapon Damage while Dual Wielding", 
                "6% increased Attack Speed while Dual Wielding", 
                "Attack Skills deal 24% increased Damage with Ailments while Dual Wielding"
            ], 
            "type": "notable", 
            "x": 0.19437939110070257, 
            "y": -0.5409836065573771
        }, 
        {
            "name": "Disciple of the Slaughter", 
            "passives": [
                "+1 to Minimum Frenzy Charges", 
                "5% chance to gain a Frenzy Charge on Kill", 
                "5% increased Damage per Frenzy Charge"
            ], 
            "type": "notable", 
            "x": 0.30210772833723654, 
            "y": 0.8337236533957846
        }, 
        {
            "name": "Vigour", 
            "passives": [
                "+1 to Maximum Endurance Charges"
            ], 
            "type": "notable", 
            "x": -0.38875878220140514, 
            "y": -0.06557377049180328
        } 
      //   ....  {...} more notes
        ], 
  "socket": {
        "index": 1, 
        "name": "DuelistBelow"
    }
}
```


JS error:
```
viewer.js:27 Uncaught TypeError: Cannot read property 'type' of undefined
    at FileReader.<anonymous> (viewer.js:27)
```

```
      if(!jewels.hasOwnProperty(file.name)) {
                        $("#jewelsTable").append(`
                        <tr>
                            <td><a href="javascript:;" onclick="changeTable('${file.name}')">${json.info.type}</a></td>
```


Would be very kind of you if you can investigate it :)
